### PR TITLE
feat : Added Slider

### PR DESCRIPTION
**Pull request by romabulani**
- Default slider 
- 
image

### CODE REVIEW

**Review by samyakshah3008 — APPROVED** [review]
Loved the feature of slider, good to merge!

**Review by thegeorgenikhil — APPROVED** [review]
Good to merge!

**Review by varnita619 — APPROVED** [review]
Good use of meta tags. Looks good to go

**Comment by romabulani** [comment]
> Loved the feature of slider, good to merge!

Thankyou :)

**Pull request merged**
